/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameDatacheckMsg.java
 *
 * Created on 2011-3-30, 23:01:08
 */
package Modules;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Administrator
 */
public class JFrameDatacheckMsg extends javax.swing.JFrame {

    /** Creates new form JFrameDatacheckMsg */
    public JFrameDatacheckMsg() {
        initComponents();
        int iThisWidth = 920;
        int iThisHight = 430;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - iThisWidth) / 2;
        int y = (screen.height - iThisHight) / 2;
        this.setBounds(x, y, iThisWidth, iThisHight);
        jTextArea1.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("查询数据完整性");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("        由于数据维护工作量较大，为保证系统的数据完整性，本系统提供了“数据完整性”的统计表，共用户查询：\n\n(一) 第2、3、4三个表所表示的数据日期必须相同，他们所对应的数据是计算“考核指标”与“盈亏分析”的基础数据\n\n(二) 对2010年就上线使用本系统的用户，表1所表示的数据可能少于表2，是因为“月末资产数据”接口是2011年3月公司信息技术部的\n    “数据中心”才补充的数据接口。由于“考核指标”与“盈亏分析”的计算程序很复杂，且已经过三个营业部近一年的运行和验证，\n     结果基本正确，为保持系统的可靠性，所以系统升级时，对新的数据接口并未修改相关计算程序，而是采用数据接口转换的方法，\n     把新数据接口转换为老的数据接口。采用“数据中心”的数据是为了数据提取更方便，同时也纠正了以前采用“平均资产”来计算\n     考核指标与盈亏分析所遇到的一些不合理的数据，提高计算结果的准确性。\n\n(三) 第5个表所代表的数据是计算客户“买卖盈亏”的依据，对2010年就开始使用本系统并坚持每天都从交易系统导入“当日成交明细”\n     的用户系统会自动把所转入的成交明细按日期保存为“历史成交明细”，如果发现有数据缺失，可以从交易系统导出“历史成交明\n     细”再转入系统，数据完整后再重新执行一次“盈亏分析计算”。\n\n(四) 建议表1、2、3所对应的数据至少转入三个月以上（必须从1月分开始），再做“资产数据归档”、“计算考核指标”与“盈亏分析计算”。\n");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("取消");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(798, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameDatacheckMsg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
