/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLogin.java
 *
 * Created on 2010-4-10, 11:47:43
 */
package Modules;

import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.io.File;
import java.net.Socket;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class JFrameLogin extends javax.swing.JFrame {

    static Socket connectionFile = null;

    /** Creates new form JFrameLogin */
    public JFrameLogin() {

        initComponents();
        int iThisWidth = 400;
        int iThisHight = 300;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - iThisWidth) / 2;
        int y = (screen.height - iThisHight) / 2;
        this.setBounds(x, y, iThisWidth, iThisHight);
        Image image = null;
        try {
            image = ImageIO.read(new File("hxzqIcon1.jpg"));
            this.setIconImage(image);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getMessage());
        } catch (InstantiationException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getMessage());
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getMessage());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getMessage());
        }
        if (Main.conn == null) {
            JOptionPane.showMessageDialog(this, "数据库连接失败");
            this.dispose();
            System.exit(-1);
        }
        this.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEnter = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLableWarning = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jFormattedTextFieldUserID = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("客户服务管理系统V5.0");
        setBackground(new java.awt.Color(255, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel1.setText("操作员:");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14));
        jLabel2.setText("密  码:");

        jButtonEnter.setFont(new java.awt.Font("宋体", 0, 14));
        jButtonEnter.setText("确认");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("宋体", 0, 14));
        jButtonCancel.setText("取消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLableWarning.setFont(new java.awt.Font("宋体", 0, 14));
        jLableWarning.setForeground(new java.awt.Color(255, 51, 51));
        jLableWarning.setFocusable(false);

        jPasswordField.setFont(new java.awt.Font("宋体", 0, 18));

        jFormattedTextFieldUserID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        jFormattedTextFieldUserID.setFont(new java.awt.Font("宋体", 0, 18));
        jFormattedTextFieldUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPreparation(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEnter)
                                .addGap(47, 47, 47)
                                .addComponent(jButtonCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextFieldUserID, 0, 0, Short.MAX_VALUE)
                                    .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLableWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter))
                .addGap(18, 18, 18)
                .addComponent(jLableWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        try {
            String UserID = jFormattedTextFieldUserID.getText();
            char[] password2 = jPasswordField.getPassword();
            String password1 = String.valueOf(password2);

            PreparedStatement SqlStatement = Main.conn.prepareStatement("execute sp_user_login ?,?");
            SqlStatement.setString(1, UserID);
            SqlStatement.setString(2, password1);

            boolean HasResult = SqlStatement.execute();
            while (!HasResult) {
                HasResult = SqlStatement.getMoreResults();
            }
            if (HasResult) {
                ResultSet SqlResult = SqlStatement.getResultSet();
                while (SqlResult.next()) {
                    int ReturnStatus = SqlResult.getInt("ret_status");
                    String ReturnMessage = SqlResult.getString("ret_msg");
                    if (ReturnStatus < 0) {
                        JOptionPane.showMessageDialog(this, ReturnMessage);
                    } else {
                        getUserInfo(UserID);
                        this.setVisible(false);
                        new MainMenu().setVisible(true);
                    }
                }
            }
            SqlStatement.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed
    public void getUserInfo(String UserID) {
        PreparedStatement SqlStatement;
        try {
            SqlStatement = Main.conn.prepareStatement("execute get_user_info ?");
            SqlStatement.setString(1, UserID);
            Boolean HasResult = SqlStatement.execute();
            while (!HasResult) {
                HasResult = SqlStatement.getMoreResults();
            }
            if (HasResult) {
                ResultSet SqlResult = SqlStatement.getResultSet();
                while (SqlResult.next()) {
                    user_id = SqlResult.getInt(1);
                    // user_id=user_id1;
                    user_name = SqlResult.getString(2).trim();
                    group_id = SqlResult.getInt(3);
                    group_name = SqlResult.getString(4);
                    password = SqlResult.getString(5);
                }
            }
            SqlStatement.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getMessage());
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }
    }

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        try {
            if (Main.conn != null) {
                Main.conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFrameLogin.class.getName()).log(Level.SEVERE, null, ex);
            Main.logger.warning(ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage());
        }

        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void InputPreparation(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPreparation
        jLableWarning.setText("");
        jFormattedTextFieldUserID.setText("");
        jPasswordField.setText("");
    }//GEN-LAST:event_InputPreparation

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JFormattedTextField jFormattedTextFieldUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLableWarning;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables
    public static int user_id;
    public static String user_name;
    public static int group_id;
    public static String group_name;
    public static String password;
}

