/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameUserPermision.java
 *
 * Created on 2012-7-3, 8:04:06
 */
package Modules;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Administrator
 */
public class JFrameUserPermision extends javax.swing.JFrame {

    Vector columnType = new Vector();
    boolean addSerial = true;

    /** Creates new form JFrameUserPermision */
    public JFrameUserPermision() {
        initComponents();
        int iThisWidth = 1022;
        int iThisHight = 720;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - iThisWidth) / 2;
        int y = (screen.height - iThisHight) / 2;
        this.setBounds(x, y - 10, iThisWidth, iThisHight);
        MouseListener PopupListener = new PopupListener(jPopupMenu1);
        //this.addMouseListener(PopupListener);
        this.jTable2.addMouseListener(PopupListener);
        getUserList();

        //注册键盘监听器，监听键盘动作，把系统无操作等待计时器置0;对非管理员屏蔽批量数据复制
        MainMenu.registerKeyListener(jTable1);
        MainMenu.registerKeyListener(jTable2);
        //注册鼠标动作监听器，监听鼠标动作，把系统无操作等待计时器置0
        MainMenu.registerMouseListener(this);
        MainMenu.registerMouseListener(jTable1);
        MainMenu.registerMouseListener(jTable2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPopupMenu1.setLabel("权限标志");

        jMenuItem1.setText("禁止");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("允许");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("用户授权");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("单击列头可按列排序");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setToolTipText("点左键选择记录，点右键打开操作菜单");
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setToolTipText("单击列头可按列排序");
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable3.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setText("添加");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("删除");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("说明");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("退出");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("系统完整菜单项");

        jLabel2.setText("用户限菜单项");

        jLabel1.setText("用户列表");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(333, 333, 333)
                .addComponent(jLabel3)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)
                        .addComponent(jButton3)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        Object S_O = jTable1.getValueAt(r, 1);
        String S = "";
        Integer user_id = 0;
        if (S_O != null) {
            S = S_O.toString();
            user_id = Integer.valueOf(S);
        }
        String sql = "execute get_user_menu " + user_id;
        JDBTableModel dm = new JDBTableModel(jTable2);
        addSerial = false;
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);
}//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int r1 = jTable1.getSelectedRow();
        if (r1 < 0) {
            JOptionPane.showMessageDialog(this, "请先点击选择角色记录 !");
            return;
        }
        Object S1 = jTable1.getValueAt(r1, 1);
        Object S2 = jTable1.getValueAt(r1, 2);
        String user_id = "0";
        String user_name = "";
        if (S1 != null) {
            user_id = S1.toString();
        }
        if (S2 != null) {
            user_name = S2.toString();
        }
        int r2 = jTable3.getSelectedRow();
        if (r2 < 0) {
            JOptionPane.showMessageDialog(this, "请先点击选择系统菜单项 !");
            return;
        }
        String serial = "0";
        String menu_id = "1";
        String menu_name = "2";
        String flag = "允许";
        Object S0_O = jTable3.getValueAt(r2, 0);
        Object S1_O = jTable3.getValueAt(r2, 1);
        Object S2_O = jTable3.getValueAt(r2, 2);
        if (S0_O != null) {
            serial = S0_O.toString();
        }
        if (S1_O != null) {
            menu_id = S1_O.toString();
        }
        if (S2_O != null) {
            menu_name = S2_O.toString();
        }

        String sql = "add_user_menu " + serial + "," + user_id + ",'" + user_name + "','";
        sql = sql + menu_id + "','" + menu_name + "','" + flag + "'";
        System.out.println(sql);
        SqlExecutor executor = new SqlExecutor();
        executor.execute(Main.conn, sql);

        sql = "execute get_user_menu " + user_id;
        JDBTableModel dm = new JDBTableModel(jTable2);
        addSerial = false;
        System.out.println(sql);
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int r1 = jTable1.getSelectedRow();
        if (r1 < 0) {
            JOptionPane.showMessageDialog(this, "请先点击选择角色记录 !");
            return;
        }
        Object S = jTable1.getValueAt(r1, 1);
        String user_id = "0";
        if (S != null) {
            user_id = S.toString();
        }
        int r2 = jTable2.getSelectedRow();
        if (r2 < 0) {
            JOptionPane.showMessageDialog(this, "请先点击选择要删除的角色菜单项 !");
            return;
        }
        String serial = "0";
        String menu_id = "1";
        Object S0_O = jTable2.getValueAt(r2, 2);
        Object S1_O = jTable2.getValueAt(r2, 3);

        if (S0_O != null) {
            serial = S0_O.toString();
        }
        if (S1_O != null) {
            menu_id = S1_O.toString();
        }

        String sql = "delete_user_menu " + user_id + ",'" + menu_id + "'";
        System.out.println(sql);
        SqlExecutor executor = new SqlExecutor();
        executor.execute(Main.conn, sql);

        sql = "execute get_user_menu " + user_id;
        JDBTableModel dm = new JDBTableModel(jTable2);
        addSerial = false;
        System.out.println(sql);
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);
}//GEN-LAST:event_jButton3ActionPerformed

    private void getUserList() {

        JDBTableModel dm = new JDBTableModel(jTable1);
        String sql = "execute get_user_list 6";
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);


        JDBTableModel dm3 = new JDBTableModel(jTable3);
        sql = "execute get_sys_menu";
        addSerial = false;
        dm3.fetchDataToTable(Main.conn, sql, columnType, addSerial);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new JFrameMsg4().setVisible(true);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //JOptionPane.showMessageDialog(this, "允许该操作");
        String flag = "禁止";
        int r1 = jTable1.getSelectedRow();
        if (r1 < 0) {
            JOptionPane.showMessageDialog(this, "请左键先点击选择用户 !");
            return;
        }
        Object S = jTable1.getValueAt(r1, 1);
        String user_id = "0";
        if (S != null) {
            user_id = S.toString();
        }
        int r2 = jTable2.getSelectedRow();
        if (r2 < 0) {
            JOptionPane.showMessageDialog(this, "请先左键点击选择用户菜单项 !");
            return;
        }
        String serial = "0";
        String menu_id = "1";
        Object S0_O = jTable2.getValueAt(r2, 2);
        Object S1_O = jTable2.getValueAt(r2, 3);

        if (S0_O != null) {
            serial = S0_O.toString();
        }
        if (S1_O != null) {
            menu_id = S1_O.toString();
        }

        String sql = "set_user_menu_flag " + user_id + ",'" + menu_id + "','" + flag + "'";
        System.out.println(sql);
        SqlExecutor executor = new SqlExecutor();
        executor.execute(Main.conn, sql);

        sql = "execute get_user_menu " + user_id;
        JDBTableModel dm = new JDBTableModel(jTable2);
        addSerial = false;
        System.out.println(sql);
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //JOptionPane.showMessageDialog(this, "禁止该操作");
        String flag = "允许";
        int r1 = jTable1.getSelectedRow();
        if (r1 < 0) {
            JOptionPane.showMessageDialog(this, "请左键先点击选择用户 !");
            return;
        }
        Object S = jTable1.getValueAt(r1, 1);
        String user_id = "0";
        if (S != null) {
            user_id = S.toString();
        }
        int r2 = jTable2.getSelectedRow();
        if (r2 < 0) {
            JOptionPane.showMessageDialog(this, "请先左键点击选择用户菜单项 !");
            return;
        }
        String serial = "0";
        String menu_id = "1";
        Object S0_O = jTable2.getValueAt(r2, 2);
        Object S1_O = jTable2.getValueAt(r2, 3);

        if (S0_O != null) {
            serial = S0_O.toString();
        }
        if (S1_O != null) {
            menu_id = S1_O.toString();
        }

        String sql = "set_user_menu_flag " + user_id + ",'" + menu_id + "','" + flag + "'";
        System.out.println(sql);
        SqlExecutor executor = new SqlExecutor();
        executor.execute(Main.conn, sql);

        sql = "execute get_user_menu " + user_id;
        JDBTableModel dm = new JDBTableModel(jTable2);
        addSerial = false;
        System.out.println(sql);
        dm.fetchDataToTable(Main.conn, sql, columnType, addSerial);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    class PopupListener extends MouseAdapter {

        JPopupMenu popupMenu;

        PopupListener(JPopupMenu popupMenu) {
            this.popupMenu = popupMenu;
        }

        @Override
        public void mousePressed(MouseEvent e) {
            showPopupMenu(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            showPopupMenu(e);
        }

        private void showPopupMenu(MouseEvent e) {
            if (e.isPopupTrigger()) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
