package Modules;


import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameMsg4.java
 *
 * Created on 2012-7-4, 15:19:47
 */

/**
 *
 * @author Administrator
 */
public class JFrameMsg4 extends javax.swing.JFrame {

    /** Creates new form JFrameMsg4 */
    public JFrameMsg4() {
        initComponents();
                int iThisWidth = 550;
        int iThisHight = 550;
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width - iThisWidth) / 2;
        int y = (screen.height - iThisHight) / 2;
        this.setBounds(x, y - 10, iThisWidth, iThisHight);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("用户授权说明");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("                用户授权说明：\n用户的菜单操作权限具有两个特征：\n1.权限叠加：即用户的最终操作权限是由该用户所属角色的菜单权限与他自己的菜单\n  权限叠加组合而成；\n2.权限屏蔽：用户菜单的权限标志被缺省设为“允许”，如被设为禁止，则可以屏蔽\n  他的相应角色菜单权限，例如：某用户属于“服务员”角色，此角色本来拥有“服\n  务管理-客户回访”的菜单权限，但是可以为该用户单独添加一个相同菜单项，并\n  把“权限标志”设为“禁止”，那么最终该用户的“客户回访”权限就被屏蔽掉；\n\n操作要领如下：\n1.首先点击选择要要授权的用户，系统会立刻列出该用户被单独授予的菜单项，但\n  不会列出其所属角色的菜单项；\n2.要添加该用户的权限菜单项，先点击选择系统菜单中的所需菜单项，然后点击\n  “添加”按钮；\n3.要删除该用户的某个权限菜单项，先点击选择该菜单项，再点击“删除”按钮；\n4.要屏蔽该用户的角色菜单项，先点击左键选择该用户菜单项，再点击右键打开\n  \"权限标志\"菜单并选择“禁止”；\n5.上述所有操作会立即写入数据库，操作完毕可立即退出界面；\n6.要添加多级菜单的某个子项，必须按自上而下的搜索路径依次添加其上各级菜\n  单项，但添加要“禁止”的菜单项时，不必添加上级菜单项。\n  ");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("取消");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMsg4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
